apiVersion: v1
kind: Service
metadata:
    name: accountservice
    namespace: kenfo-test
spec:
    selector:
        app: accountservice
    ports:
      - port: 6767
        targetPort: 6767
        protocol: TCP
    type: NodePort
